/**
 * Swagger Universitary - OpenAPI 3.0
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Event { 
    id?: number;
    name?: string;
    idType?: number;
    idUser?: number;
    date?: string;
    duration?: string;
    lieu?: string;
    description?: string;
}

